version: '2.27'

services:
  file-reader:
    build:
      context: ./file_reader
      dockerfile: Dockerfile
    container_name: file_reader
    ports:
      - "8001:8001" # host_port:container_port
    volumes:
      - ./file_reader/file_reader:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/"]
      interval: 30s
      timeout: 10s
      retries: 3

  script-scanner:
    build:
      context: ./script_scanner
      dockerfile: Dockerfile
    container_name: script_scanner
    ports:
      - "8002:8002"
    volumes:
      - ./script_scanner/script_scanner:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/"]
      interval: 30s
      timeout: 10s
      retries: 3

  uploder:
    build: 
      context: ./uploader
      dockerfile: Dockerfile
    container_name: uploader
    ports:
      - "8004:8004"
      - "5000:5000"
    volumes:
      - ./uploader/uploader:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      

  orchestrator:
    build:
      context: ./orchestrator
      dockerfile: Dockerfile
    container_name: orchestrator
    volumes:
      - ./orchestrator/orchestrator:/app 
    ports:
      - "8000:8000"
    depends_on:
      - file-reader
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  orm:
    build:
      context: ./orm
      dockerfile: Dockerfile
    container_name: orm
    ports:
      - "8003:8003"
    volumes:
      - ./orm/orm:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/"]
      interval: 30s
      timeout: 10s
      retries: 3


  postgresql:
    image: docker.io/bitnami/postgresql:16
    container_name: orm_postgresql
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_USERNAME=mandel94
      - POSTGRESQL_PASSWORD=m4rm0l4d4
      - POSTGRESQL_DATABASE=scripts_db
      - BITNAMI_DEBUG=true

volumes:
  postgresql_data:
    driver: local    





